<body>
    <div class="main-presentation" style="margin: 0px auto; max-width: 1200px; background-color:#f0f1f4;font-family: helvetica,arial,sans-serif;">
        <div class="main-textcontent" style="margin: 0px auto; border-left: 1px dotted #d2d3d5; border-right: 1px dotted #d2d3d5; width: 840px; background-color:#fff;border-top: 5px solid #544766;" cellspacing="0" cellpadding="0" align="center">
            <a href="https://www.imagerecycle.com/" target="_blank"> <img src="https://www.imagerecycle.com/images/Notification-mail/logo-image-recycle.png" alt="logo image recycle" width="500" height="84" class="CToWUd" style="display: block; outline: medium none; text-decoration: none; margin-left: auto; margin-right: auto; margin-top:15px;" /> </a>
            <p style="background-color: #ffffff; color: #445566; font-family: helvetica,arial,sans-serif; font-size: 24px; line-height: 24px; padding-right: 10px; padding-left: 10px;" align="center"><strong>Welcome on board!<br /></strong></p>
            <p style="background-color: #ffffff; color: #445566; font-family: helvetica,arial,sans-serif; font-size: 14px; line-height: 22px; padding-left: 20px; padding-right: 20px; text-align: center;">
                ImageRecycle will help you to optimize automatically your website images & PDF<br />In order to start the optimization process, you need to add an API Key and secret in the extension configuration.<br />Register a free trial account by following the link bellow or subscribe a membership to get your API key. You can also try live optimization with our uploader. Enjoy!</p>
            </p>
            <p ><a style="width: 200px; height: 35px; background: #554766; font-size: 12px; line-height: 18px; text-align: center;  margin-right:4px;color: #fff;font-size: 14px;text-decoration: none; text-transform: uppercase; padding: 8px 20px; font-weight:bold;" href="https://www.imagerecycle.com/plans/free-trial-plan?group_id=0" target="_blank" style="font-family: helvetica,sans-serif; font-size: 18px; line-height: 18px; color: #fff; text-decoration: none; display: block; padding: 10px;">Free trial</a>
                <a style="width: 200px; height: 35px; background: #554766; font-size: 12px; line-height: 18px; text-align: center;  margin-right:4px;color: #fff;font-size: 14px;text-decoration: none; text-transform: uppercase; padding: 8px 20px; font-weight:bold;" href="https://www.imagerecycle.com/index.php?option=com_content&view=article&id=2&Itemid=185" target="_blank" style="font-family: helvetica,sans-serif; font-size: 18px; line-height: 18px; color: #fff; text-decoration: none; display: block; padding: 10px;">Prices</a>
                <a style="width: 200px; height: 35px; background: #554766; font-size: 12px; line-height: 18px; text-align: center; margin-right:4px;color: #fff;font-size: 14px;text-decoration: none; text-transform: uppercase; padding: 8px 20px;font-weight:bold;" href="https://www.imagerecycle.com/index.php?option=com_ioa&amp;view=uploader&amp;Itemid=190" target="_blank" style="font-family: helvetica,sans-serif; font-size: 18px; line-height: 18px; color: #fff; text-decoration: none; display: block; padding: 10px;">Uploader</a>
            </p>
            <p style="background-color: #ffffff; color: #445566; font-family: helvetica,arial,sans-serif; font-size: 24px; line-height: 24px; padding-right: 10px; padding-left: 10px;" align="center"><strong><br />Why ImageRecycle?<br /></strong></p>
            <p style="background-color: #ffffff; color: #445566; font-family: helvetica,arial,sans-serif; font-size: 14px; line-height: 22px; padding-left: 20px; padding-right: 20px; text-align: center;"> ImageRecycle compress your image and PDF and keep the quality.<br />Images represent 60% to 70% of website page weight. Image optimization is good for your users and for your server.<br /> You won't find any other service that compress in the same time .pdf .jpeg and .png images keeping the original quality. We are using a unique algorithm to achieve that. Each compression script is executed on an optimized server to serve you as fast as possible.</p>
            <p style="text-align: center; color: #9da2a8; font-size: 11px; line-height: 12px; padding: 15px;"><br /> This is a welcome screen to help you with ImageRecycle configuration. Once you have registered your API key this message will no longer be displayed.<br /><br /><a href="https://www.facebook.com/imagerecycle" target="_blank"><img src="https://www.imagerecycle.com/images/Notification-mail/facebook.png" alt="facebook" width="24" height="24" class="CToWUd" /></a> &nbsp; <a href="https://twitter.com/ImageRecycle" target="_blank" style="margin: 0 5px;"><img src="https://www.imagerecycle.com/images/Notification-mail/twitter.png" alt="twitter" width="24" height="24" class="CToWUd" /></a> &nbsp; <a href="https://plus.google.com/104235881525310825230/posts" target="_blank"><img src="https://www.imagerecycle.com/images/Notification-mail/google.png" alt="google" width="24" height="24" class="CToWUd" /></a></p>
        </div>
    </div>								
</body>
